name: Argon2 Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/argon2-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential git
          git clone --recursive --branch 20190702 https://github.com/P-H-C/phc-winner-argon2.git
          cd phc-winner-argon2
          make OPTTARGET=x86-64
          mv libargon2.so.1 libargon2.so
      - uses: actions/upload-artifact@v2
        with:
          name: libargon2.so
          path: phc-winner-argon2/libargon2.so
