name: BlingFire Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/blingfire-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch v0.1.3 https://github.com/microsoft/BlingFire.git
          cd BlingFire
          rm -r blingfiretools/any_test
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: blingfiretokdll.dll
          path: BlingFire/build/Release/blingfiretokdll.dll
