name: cmfrec Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/cmfrec-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          brew uninstall --ignore-dependencies libomp
          git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
          cd cmfrec
          git checkout ccdd1d44c3a496c6b0e688a8f69dbf16011dd324
          cmake -B build -DCMAKE_VERBOSE_MAKEFILE=ON
          cmake --build build

          mkdir dist
          cp build/libcmfrec.dylib dist
          cp LICENSE dist/LICENSE
          cp inst/COPYRIGHTS dist/COPYRIGHTS
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v3
        with:
          name: cmfrec-3.4.2-x86_64-darwin
          path: cmfrec/dist
