name: Faiss Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/faiss-mac.yml

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - run: |
          brew install libomp
          git clone --recursive --branch v1.6.1 https://github.com/facebookresearch/faiss.git
          cd faiss
          ./configure --without-cuda ac_cv_prog_cxx_openmp="-Xpreprocessor -fopenmp" LIBS=-lomp
          make
          cd c_api
          sed -i '' 's/--whole-archive/-all_load/g' Makefile
          sed -i '' 's/--no-whole-archive/-noall_load/g' Makefile
          make
          cd ..
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v1
        with:
          name: libfaiss.dylib
          path: faiss/libfaiss.dylib
      - uses: actions/upload-artifact@v1
        with:
          name: libfaiss_c.dylib
          path: faiss/c_api/libfaiss_c.dylib
