name: Faiss Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/faiss-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential cmake git libblas-dev liblapack-dev
          git clone --recursive --branch v1.6.1 https://github.com/facebookresearch/faiss.git
          cd faiss
          ./configure --without-cuda
          make
          cd c_api
          make
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v1
        with:
          name: libfaiss.so
          path: faiss/libfaiss.so
      - uses: actions/upload-artifact@v1
        with:
          name: libfaiss_c.so
          path: faiss/c_api/libfaiss_c.so
