name: Interpret Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/interpret-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch v0.2.3 https://github.com/interpretml/interpret.git
          cd interpret
          set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
          .\build.bat
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: lib_ebm_native_win_x64.dll
          path: interpret/staging/lib_ebm_native_win_x64.dll
