name: Interpret Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/interpret-mac-arm.yml

jobs:
  build:
    runs-on: macos-11
    steps:
      - run: |
          git clone --recursive --branch v0.2.7 https://github.com/interpretml/interpret.git
          cd interpret
          sed -i '' 's/clang_pp_bin=clang++/clang_pp_bin="clang++ -target arm64-apple-macos11"/g' build.sh
          sed -i '' 's/-march=core2/-march=armv8-a/g' build.sh
          sh build.sh
          file staging/lib_ebm_native_mac_x64.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v2
        with:
          name: lib_ebm_native_mac_x64.dylib
          path: interpret/staging/lib_ebm_native_mac_x64.dylib
