name: LIBMF Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/libmf-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu git make
          git clone --recursive --branch mf_read_problem https://github.com/ankane/libmf-1.git libmf
          cd libmf
          sed -i 's/-march=native/-march=armv8-a/g' Makefile
          make all lib CXX=aarch64-linux-gnu-g++ DFLAG="" OMPFLAG=""
          mv libmf.so.2 libmf.arm64.so
      - uses: actions/upload-artifact@v2
        with:
          name: libmf.arm64.so
          path: libmf/libmf.arm64.so
