name: LIBMF Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/libmf-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch mf_read_problem https://github.com/ankane/libmf-1.git libmf
          cd libmf
          sed -i '' 's/-march=native/-march=nehalem/g' Makefile
          make all lib DFLAG="" OMPFLAG=""
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v1
        with:
          name: libmf.dylib
          path: libmf/libmf.2.dylib
