name: LIBMF Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/libmf-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch mf_read_problem https://github.com/ankane/libmf-1.git libmf
          cd libmf
          sed -i -e 's/ \/D "USEOMP" \/openmp//g' Makefile.win
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake /E /F Makefile.win all
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: mf.dll
          path: libmf/windows/mf.dll
