name: MITIE Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/mitie-mac-arm.yml

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - run: |
          git clone --recursive --branch v0.7 https://github.com/mit-nlp/MITIE.git
          cd MITIE/mitielib
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES=arm64
          make -j4
          file libmitie.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v2
        with:
          name: libmitie.dylib
          path: MITIE/mitielib/build/libmitie.dylib
