name: Multicore t-SNE Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/multicore-tsne-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch master https://github.com/DmitryUlyanov/Multicore-TSNE.git
          cd Multicore-TSNE/multicore_tsne
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: tsne_multicore.dll
          path: Multicore-TSNE/multicore_tsne/build/Release/tsne_multicore.dll
