name: Multicore t-SNE Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/multicore-tsne-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          brew install cmake libomp
          git clone --recursive --branch master https://github.com/ankane/Multicore-TSNE.git
          cd Multicore-TSNE/multicore_tsne
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_C_LIB_NAMES=omp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES=omp -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib
          make -j4
          mv libtsne_multicore.so libtsne_multicore.openmp.dylib
          cd ..
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v3
        with:
          name: libtsne_multicore.openmp.dylib
          path: Multicore-TSNE/multicore_tsne/build/libtsne_multicore.openmp.dylib
