name: NGT Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/ngt-mac.yml

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      # half license from https://sourceforge.net/p/half/code/HEAD/tree/tags/release-2.2.0/LICENSE.txt
      # grep checks source code version
      - uses: actions/checkout@v6
      - run: |
          brew install libomp
          git clone --recursive --branch v2.6.0 https://github.com/yahoojapan/NGT
          cd NGT
          cmake -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DNGT_MARCH_NATIVE_DISABLED=ON -DNGT_QBG_DISABLED=ON -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_C_LIB_NAMES=omp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES=omp -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib
          cmake --build build

          grep -F "Version 2.2.0" lib/NGT/half.hpp

          mkdir dist
          cp build/lib/NGT/libngt.dylib dist
          cp LICENSE dist/LICENSE-ngt.txt
          cp ../extra/NGT/LICENSE-half.txt dist
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v7
        with:
          name: ngt-2.6.0-x86_64-darwin
          path: NGT/dist
