name: Prophet Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/prophet-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential python3-pip wget

          pip3 install strata-cli

          wget -q https://github.com/facebook/prophet/archive/refs/tags/v1.1.tar.gz
          tar xzf v1.1.tar.gz
          cp prophet-1.1/python/stan/prophet.stan .

          strata prophet.stan -o dist
          cp prophet-1.1/LICENSE dist/licenses/prophet-license.txt
      - uses: actions/upload-artifact@v3
        with:
          name: prophet-1.1-x86_64-linux
          path: dist
