name: SCS Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/scs-mac-arm.yml

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - run: |
          git clone --recursive --branch v2.1.2 https://github.com/cvxgrp/scs.git
          cd scs
          make CC="gcc -target arm64-apple-macos11"
          file out/libscsindir.dylib
          file out/libscsdir.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v2
        with:
          name: libscsindir.dylib
          path: scs/out/libscsindir.dylib
      - uses: actions/upload-artifact@v2
        with:
          name: libscsdir.dylib
          path: scs/out/libscsdir.dylib
