name: ThunderSVM Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/thundersvm-mac.yml

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - run: |
          brew install cmake libomp
          git clone --recursive --branch master https://github.com/Xtra-Computing/thundersvm
          cd thundersvm
          mkdir build
          cd build
          cmake .. -DUSE_CUDA=OFF -DCMAKE_CXX_FLAGS=-march=nehalem -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          make -j4
          cd ..
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v1
        with:
          name: libthundersvm.dylib
          path: thundersvm/build/lib/libthundersvm.dylib
