name: xLearn Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/xlearn-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          brew install cmake
          git clone --branch v0.4.4 https://github.com/aksnzhy/xlearn.git
          cd xlearn
          sed -i '' 's/-march=native/-march=nehalem/g' CMakeLists.txt
          mkdir build
          cd build
          cmake .. -DCMAKE_MACOSX_RPATH=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v2
        with:
          name: libxlearn_api.dylib
          path: xlearn/build/lib/libxlearn_api.dylib
