name: xLearn Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/xlearn-linux.yml

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - run: |
          sudo apt install cmake
          git clone --branch v0.4.4 https://github.com/aksnzhy/xlearn.git
          cd xlearn
          sed -i 's/-march=native/-march=nocona/g' CMakeLists.txt
          sed -i 's/get_log_file(hyper_param_.log_file)/hyper_param_.log_file/g' src/solver/solver.cc
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v2
        with:
          name: libxlearn_api.so
          path: xlearn/build/lib/libxlearn_api.so
